working_dir: out
version: 0.0.0
artifact_name: clp-package-ubuntu-focal
build_parallelism: 0   # 0 -> attempt to compile with available cores on the machine
builder_dockerhub_image: whywhywhywhywhywhy/builders:x86-ubuntu-focal-20210915
components:
  - name: package-template
    type: local
  - name: compression-job-handler
    type: local
  - name: job-orchestration
    type: local
  - name: clp-py-utils
    type: local
  - name: core
    type: local